version: '3.1'

services:

  db:
    image: postgres:13.4-alpine3.14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
        - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080

  keycloak:
    image: jboss/keycloak:15.0.1
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
        - 9080:8080
